spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/accountdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect