spring:
  h2.console:
    enabled: true
    settings:
      web-allow-others: true
  datasource:
    url: jdbc:h2:mem:account;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;
    username: user
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
  flyway:
    locations: "classpath:db/migration,classpath:db/dev"
